config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nota_fiscals
  resources :pedidos
  resources :item_pedidos
  resources :endereco_clientes
  resources :marcas
  resources :clientes
  resources :produtos
  resources :plano_pgtos
  resources :tipo_pgtos
  resources :sub_categoria
  resources :departamentos
  resources :categoria
  resources :marcas 
  resources :home 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorium.rb
class Categorium < ApplicationRecord
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/endereco_cliente.rb
class EnderecoCliente < ApplicationRecord
end

app/models/item_pedido.rb
class ItemPedido < ApplicationRecord
end

app/models/marca.rb
class Marca < ApplicationRecord
end

app/models/nota_fiscal.rb
class NotaFiscal < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/models/plano_pgto.rb
class PlanoPgto < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/models/sub_categorium.rb
class SubCategorium < ApplicationRecord
end

app/models/tipo_pgto.rb
class TipoPgto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: %i[ show edit update destroy ]

  # GET /marcas or /marcas.json
  def index
    @marcas = Marca.all
  end

  # GET /marcas/1 or /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas or /marcas.json
  def create
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to marca_url(@marca), notice: "Marca was successfully created." }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1 or /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to marca_url(@marca), notice: "Marca was successfully updated." }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1 or /marcas/1.json
  def destroy
    @marca.destroy

    respond_to do |format|
      format.html { redirect_to marcas_url, notice: "Marca was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marca_params
      params.require(:marca).permit(:codMar, :dscMar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/plano_pgtos_helper.rb
module PlanoPgtosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/tipo_pgtos_helper.rb
module TipoPgtosHelper
end

app/views/marcas/_form.html.erb
<%= form_with(model: marca) do |form| %>
  <% if marca.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
        <% marca.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :codMar, style: "display: block" %>
    <%= form.number_field :codMar %>
  </div>

  <div>
    <%= form.label :dscMar, style: "display: block" %>
    <%= form.text_field :dscMar %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/marcas/_marca.html.erb
<div id="<%= dom_id marca %>">
  <p>
    <strong>Codmar:</strong>
    <%= marca.codMar %>
  </p>

  <p>
    <strong>Dscmar:</strong>
    <%= marca.dscMar %>
  </p>

</div>

app/views/marcas/edit.html.erb
<h1>Editing marca</h1>

<%= render "form", marca: @marca %>

<br>

<div>
  <%= link_to "Show this marca", @marca %> |
  <%= link_to "Back to marcas", marcas_path %>
</div>

app/views/marcas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Marcas</h1>

<div id="marcas">
  <% @marcas.each do |marca| %>
    <%= render marca %>
    <p>
      <%= link_to "Show this marca", marca %>
    </p>
  <% end %>
</div>

<%= link_to "New marca", new_marca_path %>

app/views/marcas/new.html.erb
<h1>New marca</h1>

<%= render "form", marca: @marca %>

<br>

<div>
  <%= link_to "Back to marcas", marcas_path %>
</div>

app/views/marcas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @marca %>

<div>
  <%= link_to "Edit this marca", edit_marca_path(@marca) %> |
  <%= link_to "Back to marcas", marcas_path %>

  <%= button_to "Destroy this marca", @marca, method: :delete %>
</div>