config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nota_fiscals
  resources :pedidos
  resources :item_pedidos
  resources :endereco_clientes
  resources :marcas
  resources :clientes
  resources :produtos
  resources :plano_pgtos
  resources :tipo_pgtos
  resources :sub_categoria
  resources :departamentos
  resources :categoria
  resources :marcas 
  resources :home 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorium.rb
class Categorium < ApplicationRecord
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/endereco_cliente.rb
class EnderecoCliente < ApplicationRecord
end

app/models/item_pedido.rb
class ItemPedido < ApplicationRecord
end

app/models/marca.rb
class Marca < ApplicationRecord
end

app/models/nota_fiscal.rb
class NotaFiscal < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/models/plano_pgto.rb
class PlanoPgto < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/models/sub_categorium.rb
class SubCategorium < ApplicationRecord
end

app/models/tipo_pgto.rb
class TipoPgto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/nota_fiscals_controller.rb
class NotaFiscalsController < ApplicationController
  before_action :set_nota_fiscal, only: %i[ show edit update destroy ]

  # GET /nota_fiscals or /nota_fiscals.json
  def index
    @nota_fiscals = NotaFiscal.all
  end

  # GET /nota_fiscals/1 or /nota_fiscals/1.json
  def show
  end

  # GET /nota_fiscals/new
  def new
    @nota_fiscal = NotaFiscal.new
  end

  # GET /nota_fiscals/1/edit
  def edit
  end

  # POST /nota_fiscals or /nota_fiscals.json
  def create
    @nota_fiscal = NotaFiscal.new(nota_fiscal_params)

    respond_to do |format|
      if @nota_fiscal.save
        format.html { redirect_to nota_fiscal_url(@nota_fiscal), notice: "Nota fiscal was successfully created." }
        format.json { render :show, status: :created, location: @nota_fiscal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nota_fiscal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nota_fiscals/1 or /nota_fiscals/1.json
  def update
    respond_to do |format|
      if @nota_fiscal.update(nota_fiscal_params)
        format.html { redirect_to nota_fiscal_url(@nota_fiscal), notice: "Nota fiscal was successfully updated." }
        format.json { render :show, status: :ok, location: @nota_fiscal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nota_fiscal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota_fiscals/1 or /nota_fiscals/1.json
  def destroy
    @nota_fiscal.destroy

    respond_to do |format|
      format.html { redirect_to nota_fiscals_url, notice: "Nota fiscal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nota_fiscal
      @nota_fiscal = NotaFiscal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nota_fiscal_params
      params.require(:nota_fiscal).permit(:idNota, :idPedido, :valorNota)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/nota_fiscals_helper.rb
module NotaFiscalsHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/tipo_pgtos_helper.rb
module TipoPgtosHelper
end

app/views/nota_fiscals/_form.html.erb
<%= form_with(model: nota_fiscal) do |form| %>
  <% if nota_fiscal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(nota_fiscal.errors.count, "error") %> prohibited this nota_fiscal from being saved:</h2>

      <ul>
        <% nota_fiscal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :idNota, style: "display: block" %>
    <%= form.number_field :idNota %>
  </div>

  <div>
    <%= form.label :idPedido, style: "display: block" %>
    <%= form.number_field :idPedido %>
  </div>

  <div>
    <%= form.label :valorNota, style: "display: block" %>
    <%= form.text_field :valorNota %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/nota_fiscals/_nota_fiscal.html.erb
<div id="<%= dom_id nota_fiscal %>">
  <p>
    <strong>Idnota:</strong>
    <%= nota_fiscal.idNota %>
  </p>

  <p>
    <strong>Idpedido:</strong>
    <%= nota_fiscal.idPedido %>
  </p>

  <p>
    <strong>Valornota:</strong>
    <%= nota_fiscal.valorNota %>
  </p>

</div>

app/views/nota_fiscals/edit.html.erb
<h1>Editing nota fiscal</h1>

<%= render "form", nota_fiscal: @nota_fiscal %>

<br>

<div>
  <%= link_to "Show this nota fiscal", @nota_fiscal %> |
  <%= link_to "Back to nota fiscals", nota_fiscals_path %>
</div>

app/views/nota_fiscals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Nota fiscals</h1>

<div id="nota_fiscals">
  <% @nota_fiscals.each do |nota_fiscal| %>
    <%= render nota_fiscal %>
    <p>
      <%= link_to "Show this nota fiscal", nota_fiscal %>
    </p>
  <% end %>
</div>

<%= link_to "New nota fiscal", new_nota_fiscal_path %>

app/views/nota_fiscals/new.html.erb
<h1>New nota fiscal</h1>

<%= render "form", nota_fiscal: @nota_fiscal %>

<br>

<div>
  <%= link_to "Back to nota fiscals", nota_fiscals_path %>
</div>

app/views/nota_fiscals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @nota_fiscal %>

<div>
  <%= link_to "Edit this nota fiscal", edit_nota_fiscal_path(@nota_fiscal) %> |
  <%= link_to "Back to nota fiscals", nota_fiscals_path %>

  <%= button_to "Destroy this nota fiscal", @nota_fiscal, method: :delete %>
</div>