config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nota_fiscals
  resources :pedidos
  resources :item_pedidos
  resources :endereco_clientes
  resources :marcas
  resources :clientes
  resources :produtos
  resources :plano_pgtos
  resources :tipo_pgtos
  resources :sub_categoria
  resources :departamentos
  resources :categoria
  resources :marcas 
  resources :home 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorium.rb
class Categorium < ApplicationRecord
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/endereco_cliente.rb
class EnderecoCliente < ApplicationRecord
end

app/models/item_pedido.rb
class ItemPedido < ApplicationRecord
end

app/models/marca.rb
class Marca < ApplicationRecord
end

app/models/nota_fiscal.rb
class NotaFiscal < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/models/plano_pgto.rb
class PlanoPgto < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/models/sub_categorium.rb
class SubCategorium < ApplicationRecord
end

app/models/tipo_pgto.rb
class TipoPgto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:idProd, :dscProd, :codMar, :idCat, :valor, :qtd)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/plano_pgtos_helper.rb
module PlanoPgtosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/tipo_pgtos_helper.rb
module TipoPgtosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :idProd, style: "display: block" %>
    <%= form.number_field :idProd %>
  </div>

  <div>
    <%= form.label :dscProd, style: "display: block" %>
    <%= form.text_field :dscProd %>
  </div>

  <div>
    <%= form.label :codMar, style: "display: block" %>
    <%= form.number_field :codMar %>
  </div>

  <div>
    <%= form.label :idCat, style: "display: block" %>
    <%= form.number_field :idCat %>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.text_field :valor %>
  </div>

  <div>
    <%= form.label :qtd, style: "display: block" %>
    <%= form.number_field :qtd %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>">
  <p>
    <strong>Idprod:</strong>
    <%= produto.idProd %>
  </p>

  <p>
    <strong>Dscprod:</strong>
    <%= produto.dscProd %>
  </p>

  <p>
    <strong>Codmar:</strong>
    <%= produto.codMar %>
  </p>

  <p>
    <strong>Idcat:</strong>
    <%= produto.idCat %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= produto.valor %>
  </p>

  <p>
    <strong>Qtd:</strong>
    <%= produto.qtd %>
  </p>

</div>

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Show this produto", @produto %> |
  <%= link_to "Back to produtos", produtos_path %>
</div>

app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Produtos</h1>

<div id="produtos">
  <% @produtos.each do |produto| %>
    <%= render produto %>
    <p>
      <%= link_to "Show this produto", produto %>
    </p>
  <% end %>
</div>

<%= link_to "New produto", new_produto_path %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Back to produtos", produtos_path %>
</div>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produto %>

<div>
  <%= link_to "Edit this produto", edit_produto_path(@produto) %> |
  <%= link_to "Back to produtos", produtos_path %>

  <%= button_to "Destroy this produto", @produto, method: :delete %>
</div>